name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@main

      - name: Engine
        uses: actions/checkout@main
        with:
          repository: cmtv/erudit
          path: 'engine'

      - uses: actions/setup-node@main

      - name: Install and Build 🔧
        run: |
          npm i
          npm i -g ts-node

          cd engine
          ts-node src/cli.ts build -p ..
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .site